### ISSUE TITLE
Beacons stopped working after iOS 13 release

### ISSUE THREAD

**Issue by iamandiradu** [MacKentoch/react-native-beacons-manager#153]
### Version
1.0.1

### Platform
iOS

### OS version

iOS 12

### Steps to reproduce
1.  Don't update to iOS 13

### Expected behavior
Beacons should work as they did several days ago.

### Actual behavior
Nothing.

I've noticed that beacons stopped working on iOS (iBeacons) after the release of iOS 13. I've fixed them on iOS 13 by adding this in Info.plist
``` 
<key>NSBluetoothAlwaysUsageDescription</key>
<string>We need bluetooth permissions in order to show you merchants that are near you</string>
``` 

but it doesn't seem to do much for devices that did not upgrade to iOS 13 yet. 

Also, all beacon scanners I've tried don't detect iBeacons anymore.

Anyone encountering this problem?

**Comment by ferdiamg** [comment]
They changed way too much in iOS 13 regarding privacy in combination with Bluetooth LE (due to the recent Bluetooth localization scandals) for this library to still work. Theres a lot of work to be done for this library to work with RN>0.61.0 and or iOS 13. 

I think theres currently no option to use BLE Beacons with React Native as of iOS 13, sadly react-native-ble-plx doesn't support Beacons since iOS uses a completly different API to work with Beacons.

**Comment by iamandiradu** [comment]
Indeed, they changed a lot, but the problem is not iOS 13. iOS 13 works well, but every phone with iOS 12 I tested could not find iBeacons anymore (even with beacon scanners). Had to switch to Eddystone. I'd say that everyone already updated to 13 or is going to do it soon, so I'm closing this.

**Comment by asai569** [comment]
Can this be said for react native 0.61?
