### ISSUE TITLE
need help - ios backgroundmode

### ISSUE THREAD

**Issue by RashVenkat6795** [MacKentoch/react-native-beacons-manager#185]
I have used this code [here](https://github.com/MacKentoch/react-native-beacons-manager/blob/master/examples/samples/monitoringAndRanging.ios.js), enabled background mode

for monitoring and ranging, added local push notification to debug the entry, exit and also in beacondidrange. I'm not able to make it work in the background.It stops scanning when app moves to background(a few sec after home button tap)

Without suspending the app if i have it in background, it doesn't trigger even if it is near the beacon. And how to make it work if i just remove the app from app switcher (literally suspend the app)

Tested it in real device - iphone( ios 12, ios 13). Read through all issues but nothing did solve

@MacKentoch - Please  
Any help would be highly appreciated ! TIA

**Comment by organom** [comment]
You need to add a call to `Beacons.allowsBackgroundLocationUpdates(true)` in case of iOS in order to activate it. Added in https://github.com/MacKentoch/react-native-beacons-manager/pull/193 the missing binding to have it callable from javascript side. In my code i have it before the `startRangingBeaconsInRegion` but not sure if the order even matters.  To test, just close the app and wait for a bit, you should see in the debugger that the app comes back to life if the beacon is in range.
