### ISSUE TITLE
Background mode in IOS

### ISSUE THREAD

**Issue by wcastand** [MacKentoch/react-native-beacons-manager#21]
### Version
1.0.3 (i tried with 1.0.4 too)

### Platform
iOS

### OS version

Iphone 5S
iOS 10.2
React native cli: 2.0.1
React native : 0.43.3
React : 16.0.0-alpha.6

### Steps to reproduce

I have the Background mode in Xcode project and in Info.plist i add the key : `Privacy - Location Always Usage Description`

I practically copy paste your examples but when i quit the app, the logging in the console stop instantly and the regionDidEnter/Exit only send uuid and identifier (no information about the beacon itself):

 <details>

```javascript

/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 * @flow
 */

import React, { Component } from "react";
import {
  AppRegistry,
  StyleSheet,
  Text,
  View,
  AlertIOS,
  DeviceEventEmitter
} from "react-native";
import Beacons from "react-native-beacons-manager";
import BluetoothState from "react-native-bluetooth-state";

export default class testbg extends Component {
  constructor(props) {
    super(props);

    this.state = {
      uuid: "97800498-F50E-4923-9813-65D3875331EC",
      identifier: "demonstration",
    };

    BluetoothState.subscribe(bluetoothState => {
      if (bluetoothState === "off") {
        AlertIOS.alert(
          "Bluethooth warning",
          "Vous devez aciver votre bluetooth"
        );
      }
    });
    BluetoothState.initialize();
  }

  componentWillMount() {
    const { identifier, uuid } = this.state;
    const region = { identifier, uuid };

    DeviceEventEmitter.addListener("authorizationStatusDidChange", info =>
      console.log("authorizationStatusDidChange: ", info));

    Beacons.requestAlwaysAuthorization();
    Beacons.startRangingBeaconsInRegion(region);
    Beacons.startMonitoringForRegion(region);
    Beacons.startUpdatingLocation();
  }

  componentDidMount() {
    DeviceEventEmitter.addListener("beaconsDidRange", data =>
      console.log("ranging - beaconsDidRange data: ", data));

    DeviceEventEmitter.addListener("regionDidEnter", data =>
      console.log("monitoring - regionDidEnter data: ", data));

    DeviceEventEmitter.addListener("regionDidExit", data =>
      console.log("monitoring - regionDidExit data: ", data));
  }

  componentWillUnMount() {
    Beacons.stopMonitoringForRegion();
    Beacons.stopUpdatingLocation();

    DeviceEventEmitter.removeListener("regionDidEnter");
    DeviceEventEmitter.removeListener("regionDidExit");
  }

  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>
          Welcome to React Native!
        </Text>
        <Text style={styles.instructions}>
          To get started, edit index.ios.js
        </Text>
        <Text style={styles.instructions}>
          Press Cmd+R to reload,{"\n"}
          Cmd+D or shake for dev menu
        </Text>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#F5FCFF"
  },
  welcome: {
    fontSize: 20,
    textAlign: "center",
    margin: 10
  },
  instructions: {
    textAlign: "center",
    color: "#333333",
    marginBottom: 5
  }
});

AppRegistry.registerComponent("testbg", () => testbg);

```

</details>

### Expected behavior
Either the ranging works in background or the monitoring send the information about the beacon

### Actual behavior
Ranging doesn't trigger when in background and regionDidEnter/Exit only send the region uuid and identifier.
I did some more tests and i have a weird behavior.When i am in background (app closed). the app after a while trigger `regionDidEnter/Exit` and for a little while trigger `beaconsDidRange` but beaconsDidRange doesn't actually detect the beacons in range (empty array)

![capture d ecran 2017-04-11 a 15 47 26](https://cloud.githubusercontent.com/assets/2178244/24912487/88c58696-1ece-11e7-9d22-cef84304bb03.png)

Sometimes nothing is detected, none of the event are triggered in background.
It's seems pretty random and i don't know what's the cause.

And finally, sometimes i see the beacons when the app is in foreground but if i quit the app nothing is triggered anymore. If i reopen the app, the app trigger the event but doesn't detect any beacons.

![capture d ecran 2017-04-11 a 15 58 50](https://cloud.githubusercontent.com/assets/2178244/24912963/f4460af2-1ecf-11e7-9d49-1ebe93ad8c47.png)

**Comment by r-bansal** [comment]
@wcastand - logging may not work (I had some issues logging when in background before), and background mode only works for regions enter/exit events. Ranging beacons is not supported in the background. Do share the link to the example you followed (or your code snippet) and I can take a look and get back to you.

 Ranging works, however, you may have some scenarios where you do not range beacons (when they exist) due to timing issues (when the device scans and when the beacon broadcasts). This can be mitigated very easily (collecting a few events to confirm a beacon was ranged).

**Comment by wcastand** [comment]
This the example i used as a base: [link](https://github.com/MacKentoch/react-native-beacons-manager/tree/master/examples/BeaconsDemo) with this piece for the monitoring part [link](https://github.com/MacKentoch/react-native-beacons-manager/blob/master/examples/samples/monitoring.ios.js)

Ok, i'll try to make my notifications in local work and then try without logging then.

**Comment by r-bansal** [comment]
@wcastand, noticed one issue:

```js
Beacons.requestAlwaysAuthorization();
Beacons.startRangingBeaconsInRegion(region);
Beacons.startMonitoringForRegion(region);
Beacons.startUpdatingLocation();
```

should be 
```js
Beacons.requestAlwaysAuthorization();
Beacons.startMonitoringForRegion(region);
Beacons.startRangingBeaconsInRegion(region);
Beacons.startUpdatingLocation();
```

as per https://github.com/MacKentoch/react-native-beacons-manager/blob/master/examples/samples/monitoringAndRanging.ios.md

**Comment by MacKentoch** [comment]
Hi @wcastand 

Nothing more to add since all is already nicely covered

As you said and I agree with you, the best bet with iOS when in background is to rely on localNotifications (*or notifications in general*).

Local Notifications have more `power` in iOS so you are sure iOS won't prevent your app to get notified (*by execution time limitation or just because system consider it has more important to do at the moment*).

*I think I should also add an example of use case with background + localNotification.*
*It will help in case there some fix are needed or at least it will help using the library.*

**Comment by wcastand** [comment]
Hi,

Sorry for the response time, i was testing and trying to make things work...
So after 2 days of testing, i can't get the monitoring to work.

It never detect a beacon (in foreground and background mode).
And i don't know if it's a bug but when i use the ranging, he detects the beacons at first but if a close the app and reopen it, the listener is still logging but doesn't detect the beacons anymore.

So i was thinking that may be related to the problem with monitoring. If avec closing the app, the beaconsDidRange doesn't detect beacons anymore. Maybe the monitoring act the same and doesn't fire the event.


Device: Iphone 5S
OS: IOS 10.3
React native : 0.43.3
React: 16.0.0-alpha.6
beacons-manager : 1.0.4

This is the project i use for testing : [link](https://github.com/wcastand/testbg/tree/master)

**Comment by MacKentoch** [comment]
Hi @wcastand 

I've looked into your project code (*did not test*), as @r-bansal suggested you must correct [here](https://github.com/wcastand/testbg/blob/master/index.ios.js#L32).

You must start `monitoring` **always before** `ranging`.

Otherwise to be sure to cover all, what kind of beacon do you use? 
I mean:
- physical one
- software emulated 

AND:
- ibeacon
- eddystone
- any other kind?

If you have an alternate an `android phone` you could use [this application](https://play.google.com/store/apps/details?id=net.alea.beaconsimulator&hl=fr) since it is a complete simulator (*my preferred to be honest*) and well designed.

Otherwise even iOS [one](https://github.com/gemtot/iBeacon) (*less complete*) is ok.

Another question, it seems interesting that you have React v16.0.0-alpha.6. Did you manually installed this version?

**Comment by wcastand** [comment]
Hi,
I was on this all day, i came up with something that work. I switch ranging and monitoring.
I use physical ibeacon from Estimote.

I'm in React Alpha on the test because i have the last version of react-native-cli and they use react alpha for Fiber i think with React native 0.43. So, it's done automatically by the cli.

I still have some issues with the detection. The ranging seems to failed if i quit and then reopen the app. The Ranging is still firing event but doesn't detect my beacons anymore. At some point i have to deactivate my bluetooth and reactivate it in order to detect my beacons again.

Leaving the app and switching with monitoring and ranging seems to broke the detection somehow.

**Comment by MacKentoch** [comment]
Thanks that was really interesting.

I will upgrade the example and test.
It may come from native since like that I don't see what could me added to native code for this purpose.

Concerning ReactJS version I did not create a new app from cli since 0.43.
Thanks to you 👏  I upgrade some applications and at least I win FlatList from core React Native.

You may be right (*use of alpha for Fiber*) it is just surprising since last December I remember I heard FB saying that Fiber may not come for sure in React 16 but maybe 17 since there were so much work to be done first.

That would be really awesome it comes with React 16 and React Native needs even more the benefit of Fiber.
