### ISSUE TITLE
Preset "flow"?

### ISSUE THREAD

**Issue by kerubkim** [MacKentoch/react-native-beacons-manager#40]
I am simply getting an Error that says "Couldn't find preset "flow" relative to directory "<PATH>/node-modules/react-native-beacons-manager.

Help? :)

**Comment by MacKentoch** [comment]
Hi @kerubkim 

I don't understand you should not need...
As a fast fix, install it :

```bash
npm i --save-dev babel-preset-flow
```

**Comment by leoschweizer** [comment]
Having this problem as well. You should add the `.babelrc` to `.npmignore` and not publish it (if it is required to be pulished, that would in turn mean that the users of this library require `babel-preset-flow`)!

**Comment by dlindahl** [comment]
@MacKentoch Installing `babel-preset-flow` did not fix the problem for me. Probably because Babel should not be processing `node_modules`. I think the best practice is to pre-process library files and publish those so that everyone can use them, regardless of what their setup is.

See:
https://javascriptplayground.com/blog/2017/01/npm-flowjs-javascript/#publishing-typed-javascript-modules

**Comment by MacKentoch** [comment]
Thank you @kerubkim, @leoschweizer and @dlindahl for your feedbacks.

I've just published to nom v1.0.7 to fix that.
What I did: 
- I removed .babelrc from the lib.
*ReactNative project already handles flow types so no need to add plugins and even less need in a library.*

Thank you for you patience.

NOTE: RN 0.48 was buggy on iOS so better stick to 0.47.2 until it is fixed.

**Comment by MacKentoch** [comment]
fixed with v1.0.7
