### ISSUE TITLE
Region enter/exit events not firing

### ISSUE THREAD

**Issue by dlindahl** [MacKentoch/react-native-beacons-manager#42]
### Version
1.0.7

### Platform
iOS

### OS version

iOS 10

### Steps to reproduce
1.  Monitor region enter/exiting for a beacon
2.  Toggle beacon activation
3.  Note that no events get fired other than `didRange`

### Expected behavior
`regionDidEnter` and `regionDidExit` events should fire when moving in and out of range of a beacon

### Actual behavior
`regionDidEnter` and `regionDidExit` events do not fire at all

The code I'm using is pulled straight from the [README](https://github.com/MacKentoch/react-native-beacons-manager/blame/d9969635bea422fcd7b69f1bd574e3ff6f6d7044/README.md#L77-L113) with the exception of adding event listeners for `regionDidEnter` and `regionDidExit`:

```js
DeviceEventEmitter.addListener('regionDidEnter', data => {
  console.info('REGION ENTER!', data)
})
DeviceEventEmitter.addListener('regionDidExit', data => {
  console.info('REGION EXIT!', data)
})
```

and changing my region definition:
```js
const region = {
  identifier: 'Estimotes',
  major: 1,
  minor: 1,
  uuid: '[MY UUID]'
}
```

No matter what I do, I cannot get either of these events to fire. The only thing I see is that XCode shows the following NSLog output: `createBeaconRegion with: identifier - uuid - major - minor`

**Comment by Shauneoo** [comment]
Hello, has anyone managed to resolve this or receiving a similar behaviour?

**Comment by MacKentoch** [comment]
Working on it.

Strange issue at first sight.

I dream I left my old iPhone 5c with iOS 9 since I suspect something related to iOS 10.x...
Anyway I will fix it.

Thank you for your patience.

**Comment by ashemah** [comment]
I am also affected by this issue.
Is it due to RCTDeviceEventEmitter now being deprecated/fatal?

**Comment by MacKentoch** [comment]
Thank you @ashemah for helping.

I don't think it is related to `RCTDeviceEventEmitter` since `monitoring` and `ranging` use it both but *they aren't both affected by this issue*.

I suspected Plist new constraint but it does not seem to be the case.

Right now I honestly don't understand why this occurs. 
Still looking for the origin of the issue then it will be fixed.

**Comment by MacKentoch** [comment]
It works ([iOS example](https://github.com/MacKentoch/react-native-beacons-manager/tree/master/examples/BeaconsDemo)).

BUT `regionDidEnter` and `regionDidLeave` trigger ONLY after few seconds - **like 30 seconds (= eternity for electronics)** - (*I guess Apple wants to save battery consumption...*)

**If your application starts and beacons is already in range:  `regionDidEnter` won't trigger!!!**

<img width="375" alt="beacon-did-enter" src="https://user-images.githubusercontent.com/11223428/30627342-cffbc07c-9dcf-11e7-8e14-fea29fb94274.png">



I just added this line in my code (**it is not mandatory**) to force drop empty range:

```objective-c
Beacons.shouldDropEmptyRanges(true);
```

Ensure your `Plist` contains both keys with messages (*don't leave messages blank, it seems like Apple force now to write a message to make it work*):
- `Privacy - Location When In Use Usage Description`
- `Privacy - Location Always Usage Description`
- I even added (*but it is not sufficient itself alone so I guess it is no use*): `Privacy - Location Always and When In Use Usage Description`

![beacon-monitor](https://user-images.githubusercontent.com/11223428/30627352-deb527ca-9dcf-11e7-8706-f2fbd5b9758e.png)

**Comment by ashemah** [comment]
Hi MacKentoch. I have a working version of this now as well after forking and modifying your code. Haha - I should have waited :)

So what I did was upgrade the iOS code to use RCTEventEmitter instead of sending through the bridge. This is inline with the latest code iOS examples in the RN docs: https://facebook.github.io/react-native/docs/native-modules-ios.html

It's now sending stuff to JS very responsively. There is a bit of a delay when moving in and out of regions but that's normal (of up to 30s when off cabled power. I am seeing only 10s on power).

I am also adding a listener for:

- (void) locationManager:(CLLocationManager *)manager didDetermineState:(CLRegionState)state forRegion:(CLRegion *)region;

This will be called when you start monitoring and let you know if you are ALREADY in a region.

I'll get a pull request together for it in a bit.

**Comment by MacKentoch** [comment]
@ashemah awesome! 👏 

Your PR is welcomed, you did not did that for nothing.

It will greatly improve the librairie.

**Comment by MacKentoch** [comment]
I close this issue.

PR #46 should improve even more iOS (*already on master: beware breaking to attach event listeners: more details before v1.0.8 release*)

**Comment by eurobob** [comment]
@ashemah can we use didDetermineState to trigger an entry event if you are already in a region?

**Comment by ashemah** [comment]
Hi @eurobob yep that is right. It will be called when the app starts and will either indicate inside or outside or unknown.

**Comment by innyso** [comment]
@MacKentoch Hi, thanks for the ios example. I am tried it on my ios device. It works for ranging but not for monitoring. I understand that regionDidEnter will only get trigger when the device is not in the region when the app bootup. How about regionDidExit? I didnt seems to be able to get it trigger.
