### ISSUE TITLE
is Apple Promt "allow use blueTouth" required

### ISSUE THREAD

**Issue by Mactub07** [MacKentoch/react-native-beacons-manager#65]
### Platform
iOS 

### Expected behavior
I'm interested : is Apple Promt "allow use blueTouth" required. My app use beacons only for detect one and user location data doesn't use

### Actual behavior
What is happening

**Comment by MacKentoch** [comment]
Hi,

Beacons are `bluetooth BTLE` standard compliant devices.
So by design bluetooth is needed.

Using bluetooth in iOS requires dealing with [CLLocationManager](https://developer.apple.com/documentation/corelocation/cllocationmanager) which means you technically deal with native location.

By Design Apple prompts users when an application needs to access location (*as a privacy concern = to reinsure users that Apple don't let applications using anything on device without their consent*).
